"""add column is_active

Revision ID: 1c2b55928857
Revises: 1a5d23460a51
Create Date: 2023-08-10 15:33:01.393968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2b55928857'
down_revision: Union[str, None] = '1a5d23460a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('positions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    op.drop_column('positions', 'is_active')
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
