"""add unit_of_measurement to positions

Revision ID: b901f8fd9d5d
Revises: 8925fd466001
Create Date: 2023-08-14 11:24:17.574532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b901f8fd9d5d'
down_revision: Union[str, None] = '8925fd466001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('unit_of_measurement', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'unit_of_measurement')
    # ### end Alembic commands ###
