"""some changes

Revision ID: 8925fd466001
Revises: 1c2b55928857
Create Date: 2023-08-13 16:58:03.953592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8925fd466001'
down_revision: Union[str, None] = '1c2b55928857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'units_in_stock')
    op.add_column('products_positions', sa.Column('quantity_for_product', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_positions', 'quantity_for_product')
    op.add_column('products', sa.Column('units_in_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
