"""add primary key

Revision ID: 8f3a4580167f
Revises: b3688e6517ea
Create Date: 2023-08-17 10:34:16.757894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3a4580167f'
down_revision: Union[str, None] = '15b64fbfc73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order_details', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order_details', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('order_details', 'id')
    # ### end Alembic commands ###
