"""add on_stop_list to products

Revision ID: 1a5d23460a51
Revises: c1517a21a00e
Create Date: 2023-08-09 12:00:26.357553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5d23460a51'
down_revision: Union[str, None] = 'c1517a21a00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('on_stop_list', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'on_stop_list')
    # ### end Alembic commands ###
