"""add status to orderdetail

Revision ID: 56d957419aa4
Revises: 8f3a4580167f
Create Date: 2023-08-17 17:32:38.246699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d957419aa4'
down_revision: Union[str, None] = '8f3a4580167f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('status', sa.VARCHAR(length=128), server_default='new', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'status')
    # ### end Alembic commands ###
