"""add id to orders detail

Revision ID: b3688e6517ea
Revises: 15b64fbfc73a
Create Date: 2023-08-15 16:08:53.466580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3688e6517ea'
down_revision: Union[str, None] = '15b64fbfc73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.alter_column('order_details', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_details', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('order_details', 'id')
    # ### end Alembic commands ###
